// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertTag 
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageTag
    {
        public const string InsertTagString = "88419a58-a1cb-4cca-ba77-92c68372bc3e";
        public static Guid InsertTag = new Guid(InsertTagString);
        public const string InsertTagCommentedString = "960656b0-6e31-4854-81c8-c3ae13ca6add";
        public static Guid InsertCommentedTag = new Guid(InsertTagCommentedString);
        public const string GetTagString = "65943626-e6fd-45b1-83dd-fededc7dde95";
        public static Guid GetTag = new Guid(GetTagString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int InsertTagCmd = 0x0100;
        public const int InsertTagCommentedCmd = 0x0101;
        public const int GetTagCmd = 0x0102;
    }
}